ruptureit:
    endpoint: 'https://ruptureit.com/test.php?reflection=%s'
    prefix: 'imper'
    alphabet: 'abcdefghijklmnopqrstuvwxyz'
    secretlength: 9
    alignmentalphabet: 'ABCDEFGHIJKLMNOPQRSTUVWXYZ'
    recordscardinality: 1
dionyziz:
    endpoint: 'https://dionyziz.com/breach-test/reflect.php?ref=%s'
    prefix: 'imper'
    alphabet: 'abcdefghijklmnopqrstuvwxyz'
    secretlength: 9
    alignmentalphabet: 'ABCDEFGHIJKLMNOPQRSTUVWXYZ'
    recordscardinality: 1
dimkarakostas:
    endpoint: 'https://dimkarakostas.com/rupture/test.php?ref=%s'
    prefix: 'imper'
    alphabet: 'abcdefghijklmnopqrstuvwxyz'
    secretlength: 9
    alignmentalphabet: 'ABCDEFGHIJKLMNOPQRSTUVWXYZ'
    recordscardinality: 1
